spring.application.name=DAZMA
server.port=${PORT:8080}
server.shutdown=graceful

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.runtime.verification-enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
